services:
  - type: web
    name: sidestore-jit-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
