name: Sign iOS Shortcuts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sign-shortcuts:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure the shortcuts CLI tool is available
      - name: Verify shortcuts CLI
        run: |
          if ! command -v shortcuts &> /dev/null; then
            echo "shortcuts CLI not found. Ensure it's installed on the runner."
            exit 1
          fi

      # Find and sign all .shortcut files
      - name: Sign Shortcuts
        env:
          SIGNING_IDENTITY: ${{ secrets.SIGNING_IDENTITY }}
        run: |
          if [ -z "$SIGNING_IDENTITY" ]; then
            echo "SIGNING_IDENTITY not set. Skipping signing."
            exit 1
          fi
          find . -type f -name "*.shortcut" | while read -r file; do
            echo "Signing $file..."
            shortcuts sign --input "$file" --output "${file%.shortcut}-signed.shortcut" --identity "$SIGNING_IDENTITY"
          done

      # Upload signed artifacts
      - name: Upload signed shortcuts
        uses: actions/upload-artifact@v4
        with:
          name: signed-shortcuts
          path: |
            **/*-signed.shortcut
          if-no-files-found: warn

      # Optional: Commit signed shortcuts back to the repository
      - name: Commit signed shortcuts
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add *-signed.shortcut
          git commit -m "Add signed shortcut files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}