name: Sign iOS Shortcuts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sign-shortcuts:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure the shortcuts CLI tool is available
      - name: Verify shortcuts CLI
        run: |
          if ! command -v shortcuts &> /dev/null; then
            echo "shortcuts CLI not found. Ensure it's installed on the runner."
            exit 1
          fi

      # Verify .p12 file exists and print checksum for debugging
      - name: Verify certificate file
        run: |
          if [ ! -f "Priv/Games.p12" ]; then
            echo "Error: Priv/Games.p12 not found"
            exit 1
          fi
          echo "Checksum of Priv/Games.p12:"
          shasum -a 256 Priv/Games.p12

      # Import signing certificate
      - name: Import signing certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          echo "Importing Priv/Games.p12 (no password)"
          security import Priv/Games.p12 -k build.keychain -P "" -A -T /usr/bin/codesign -T /usr/bin/shortcuts || {
            echo "Error: Failed to import certificate"
            exit 1
          }
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain || {
            echo "Error: Failed to set key partition list"
            exit 1
          }
          echo "Listing identities in keychain:"
          security find-identity -v -p codesigning

      # Find and sign all .shortcut files
      - name: Sign Shortcuts
        run: |
          SIGNING_IDENTITY="Developer ID Application: Lynq Inc (K5S7WU9FSX)"
          echo "Using signing identity: $SIGNING_IDENTITY"
          find . -type f -name "*.shortcut" | while read -r file; do
            echo "Signing $file..."
            shortcuts sign --input "$file" --output "${file%.shortcut}-signed.shortcut" --identity "$SIGNING_IDENTITY" || {
              echo "Error: Failed to sign $file"
              exit 1
            }
          done

      # Upload signed artifacts
      - name: Upload signed shortcuts
        uses: actions/upload-artifact@v4
        with:
          name: signed-shortcuts
          path: |
            **/*-signed.shortcut
          if-no-files-found: warn

      # Optional: Commit signed shortcuts back to the repository
      - name: Commit signed shortcuts
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add *-signed.shortcut
          git commit -m "Add signed shortcut files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}