name: Sign iOS Shortcuts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sign-shortcuts:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure the shortcuts CLI tool is available
      - name: Verify shortcuts CLI
        run: |
          if ! command -v shortcuts &> /dev/null; then
            echo "shortcuts CLI not found. Ensure it's installed on the runner."
            exit 1
          fi

      # Import signing certificate from Priv folder
      - name: Import signing certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import Priv/certificate.p12 -k build.keychain -P "1234" -T /usr/bin/codesign -T /usr/bin/shortcuts
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        # Alternative using a secret (recommended):
        # env:
        #   CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        # run: |
        #   security create-keychain -p "" build.keychain
        #   security default-keychain -s build.keychain
        #   security unlock-keychain -p "" build.keychain
        #   security import Priv/certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/shortcuts
        #   security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      # Find and sign all .shortcut files
      - name: Sign Shortcuts
        run: |
          SIGNING_IDENTITY="Developer ID Application: (*K5S7WU9FSX)"
          find . -type f -name "*.shortcut" | while read -r file; do
            echo "Signing $file..."
            shortcuts sign --input "$file" --output "${file%.shortcut}-signed.shortcut" --identity "$SIGNING_IDENTITY"
          done

      # Upload signed artifacts
      - name: Upload signed shortcuts
        uses: actions/upload-artifact@v4
        with:
          name: signed-shortcuts
          path: |
            **/*-signed.shortcut
          if-no-files-found: warn

      # Optional: Commit signed shortcuts back to the repository
      - name: Commit signed shortcuts
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add *-signed.shortcut
          git commit -m "Add signed shortcut files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}